### ISSUE TITLE
LibZMQ4 and Centreon 3.4

### ISSUE THREAD

**Issue by rk4an** [centreon/centreon-vmware#43]
Hi,

The new version didn't work on Centreon 3.4 (based on CentOS 6.7). We have the following error message. Someone already find a solution? Thanks in advanced

Can't locate ZMQ/LibZMQ4.pm in @INC (@INC contains: /usr/lib/nagios/plugins/centreon-plugins /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/lib/nagios/plugins/centreon-plugins/apps/vmware/connector/custom/connector.pm line 26.
BEGIN failed--compilation aborted at /usr/lib/nagios/plugins/centreon-plugins/apps/vmware/connector/custom/connector.pm line 26.
Compilation failed in require at /usr/lib/nagios/plugins/centreon-plugins/centreon/plugins/misc.pm line 221

**Comment by garnier-quentin** [comment]
See following ticket:
https://github.com/centreon/centreon-plugins/issues/686
